---
title: "Discussion"
---

## Quality control

- QC approach
  - limitations of primer trimming
    - my method is stringent as it requires FWD and REV. This could cause bias in a real world scenario
    - make this configurable in pipeline for users
  - Although in our real world case study we still retained many sequences, indication of better basecalling

## Clustering

- Measures of species recovery
  - \# otus vs. # species vs. %loss
  - misleading - nanoclust looks like it is recovering species when min_cluster_size is high, but actually clumping unrelated taxa together.
  - nanoclust read loss + # OTUs inconsistent at larger library sizes

- Nanoclust unable to cluster large datasets
  - performance reasons
  - designed for more conserved 16S regions, care needs to be taken when applying to variable ITS regions.

- Future:
  - nanoclust might still be useful, but more complicated
    - closer study of UMAP/HDBSCAN parameters and effect on ITS clustering
    - method should not be applied blindly

## Taxonomic assignments

- Limitations of assessing correct taxonomic assignments
  - taxonomic labels not always consistent in reference DB

- At low min_cluster_size:
  - Nanoclust successful at delineating species that VSEARCH at 97% could not

- Taxonomic classification precision
  - surprisingly:
    - Nanoclust: lower unclassified and higher precision with lowest minimum OTU size
    - VSEARCH: lower classification rate when filtering small OTUs
    - consensus: introducing noise in nanoclust
      - poor performance for vsearch (explained by grouping unrelated species together)
      - future: determine source: racon or medaka?
        - explore better techniques (draft read, etc)

- some consistent false positives
  - human error?

- many OTUs unclassified in soil data
  - dnabarcoder too stringent?
  - limitation of reference database when working with Australian fungi

## Recommendations
  - best practices for running
    - minimum sample sizes for recovering rare species

## Future work
  - taking advantage of long amplicon (LSU, SSU)
    - aid unclassified species