---
title: "Conclusion"
---

We have demonstrated that ONT sequencing has emerged as a promising approach for fungal metabarcoding.
Our workflow was capable of detecting major taxa in mock communities.
However, while our approach was capable of detecting rare OTUs, it became difficult to differentiate true rare OTUs from false positives.
We have made our workflow available publicly available for use by others ([https://github.com/aringeri/nanoporcini](https://github.com/aringeri/nanoporcini)).
We confirmed existing difficulties with classifying underrepresented Australian fungal taxa in the UNITE+INSD database.
However, we feel that this presents an opportunity for long-read technology in future work by classifying more conserved regions such as the 28S (LSU) marker.
The quality of sequences produced by ONT sequencing has improved steadily over the past two years, if this trend continues
we expect the widespread adoption of this technology to continue and become commonplace among mycologists and microbial ecologists.