project:
  type: book

book:
  title: "A Workflow for Metabarcoding of Fungi with Oxford Nanopore Sequencing"
  author: Alex Ringeri
  chapters:
    - index.qmd
    - 02-Objectives.Rmd
    - 03-Significance.Rmd
    - 04-LiteratureReview.Rmd
    - 05-Methods.Rmd
    - 06-Results.Rmd
    - 07-Discussion.Rmd
    - 08-Conclusion.Rmd
    - 09-Supplementary.Rmd
    - 10-References.Rmd

bibliography: '../../references.bib'
csl: '../../bioinformatics.csl'

format:
  html:
    theme: cosmo
    number-depth: 3
  pdf:
    documentclass: scrreprt
  docx:
    toc: true
    number-sections: true
    highlight-style: github
    number-depth: 2
    reference-doc: custom-reference-doc.docx
#    reference-doc: templates/CDC_Template.docx

#fig-cap-location: top
execute:
  echo: false
crossref:
  chapters: false